guide/migration/vnode-lifecycle-events.md
NatanCieplinski/docs-next-it pull request #138
Opened 2021-03-24 08:52 UTC by theRenard

2021-03-24 08:56 UTC, theRenard commented
@NatanCieplinski su gitlab c'è la possibilità di impedire un merge se non si è passata la fase di review, forse dovremmo implementarlo anche qui ?

2021-03-24 11:03 UTC, NatanCieplinski commented
Avendo lavorato sempre con colleghi stretti, in passato abbiamo ho usato convenzioni e non delle branch rules. Ma in questo caso è un'ottima idea, grazie. L'ho implementata subito.

2021-03-24 11:12 UTC, NatanCieplinski commented on src/guide/migration/vnode-lifecycle-events.md
> +In Vue 2, era possibile utilizzare gli eventi delle fasi chiave nel ciclo di vita di un componente. Questi eventi avevano nomi che iniziavano con il prefisso `hook:`, seguito dal nome del ciclo di vi
Direi che `lifecycle hook` in un qualche modo lo dobbiamo tradurre in modo diverso da `lifecycle`. Io propongo `ciclo di vita` per `lifecycle` e `fase del ciclo di vita` per `lifecycle hook`. Leggendo però la doc di react ho visto che traducono il termine solo nella pagina dove viene introdotto il concetto di lifecycle e nel resto della doc lasciano il termine inglese, e stessa cosa per le parole `state` e `hook`. Tu che ne pensi?

2021-03-24 11:14 UTC, NatanCieplinski requested changes

2021-03-24 11:14 UTC, NatanCieplinski commented on src/guide/migration/vnode-lifecycle-events.md
> +## Guarda anche
Stessa cosa dell'altra PR. Direi di usare **Vedi anche:**

2021-03-24 11:16 UTC, NatanCieplinski commented on src/guide/migration/vnode-lifecycle-events.md
> +Nella maggior parte dei casi dovrebbe solo richiedere la modifica del prefisso. Gli hook del ciclo di vita `beforeDestroy` e` destroyed` sono stati rinominati rispettivamente in `beforeUnmount` e` un
Manca lo spazio tra **e** e `unmounted`

2021-03-24 11:49 UTC, theRenard commented on src/guide/migration/vnode-lifecycle-events.md
> +In Vue 2, era possibile utilizzare gli eventi delle fasi chiave nel ciclo di vita di un componente. Questi eventi avevano nomi che iniziavano con il prefisso `hook:`, seguito dal nome del ciclo di vi
Farei come React, ovvero lasciarlo in inglese ovunque e magari tradurlo solo quando si spiega in cosa consiste (quindi solo nella pagina del lifecycle. Mi sono posto la stessa domanda (e probabilmente avremo questa discussione altre mille volte durante la traduzione). Ci sono parole difficilmente traducibili, altre che convenzionalmente sono ormai usate sempre in inglese anche nelle traduzioni in italiano, altre che anche se hanno un senso compiuto in italiano, o suona ridicole o forzate (esempio camel case su Wikipedia esiste in `[notazione a cammello](https://it.wikipedia.org/wiki/Notazione_a_cammello)`. Orrenda e mai sentita. Invito gli altri esimi collaboratori ad esprimersi @iolk @rbattiato. In ogni caso @NatanCieplinski dopo aver scelto cosa tradurre e cosa lasciare in italiano dovremmo creare un riferimento nel wiki per gli altri traduttori, per non creare incoerenze. Ogni fonte di ispirazione è benvenuta ovviamente.

2021-03-24 11:56 UTC, theRenard commented on src/guide/migration/vnode-lifecycle-events.md
> +In Vue 2, era possibile utilizzare gli eventi delle fasi chiave nel ciclo di vita di un componente. Questi eventi avevano nomi che iniziavano con il prefisso `hook:`, seguito dal nome del ciclo di vi
Tipo così -> https://github.com/NatanCieplinski/docs-next-it/wiki/Riferimenti-per-traduttori

2021-03-24 12:32 UTC, NatanCieplinski commented on src/guide/migration/vnode-lifecycle-events.md
> +In Vue 2, era possibile utilizzare gli eventi delle fasi chiave nel ciclo di vita di un componente. Questi eventi avevano nomi che iniziavano con il prefisso `hook:`, seguito dal nome del ciclo di vi
Ottima idea quella della wiki. Come riferimento sicuro userei la guida di React, anche se non so quanto possa essere corretta la traduzione. In generale comunque andrei per il definire i termini difficilmente traducibili una volta e poi usarli in inglese. Aspetto anche io le opinioni degli altri.

2021-03-24 13:02 UTC, iolk commented on src/guide/migration/vnode-lifecycle-events.md
> +In Vue 2, era possibile utilizzare gli eventi delle fasi chiave nel ciclo di vita di un componente. Questi eventi avevano nomi che iniziavano con il prefisso `hook:`, seguito dal nome del ciclo di vi
Sono d'accordo anche io userei come riferimento React e lascerei alcuni termini cosi come sono.
La wiki mi sembra il modo migliore per tenere traccia di quali termini non convertiamo.

2021-03-25 10:21 UTC, theRenard commented
@NatanCieplinski ho fatto le modifiche richieste 👋

2021-03-25 10:46 UTC, NatanCieplinski approved these changes
LGTM

2021-03-25 11:00 UTC, merged