guide/migration/v-if-v-for.md
NatanCieplinski/docs-next-it pull request #139
Opened 2021-03-24 09:19 UTC by theRenard

2021-03-24 11:00 UTC, NatanCieplinski requested changes

2021-03-24 11:00 UTC, NatanCieplinski commented on src/guide/migration/v-if-v-for.md
> +## Guarda anche
Se non sbaglio una traduzione più corretta sarebbe **Vedi anche:**

2021-03-25 10:23 UTC, theRenard commented
Modifica `vedi anche`

2021-03-25 10:46 UTC, NatanCieplinski approved these changes

2021-03-25 11:01 UTC, merged