Add guide/installation.md translation
NatanCieplinski/docs-next-it pull request #140
Opened 2021-03-24 20:25 UTC by NatanCieplinski

La traduzione non è letterale rispetto al file precedente perchè dei conflitti di merge lo avevano un pò incasinato. Le sezioni aggiunte le ho viste direttamente dalla doc su v3.vuejs.org

2021-03-25 07:59 UTC, theRenard requested changes
Qualche suggerimento e qualche domanda aperta

2021-03-25 07:59 UTC, theRenard commented on src/guide/installation.md
>  ## Note di Rilascio
Due suggerimenti possibili, `note della versione` oppure `note della release`, che ne pensi ?

2021-03-25 07:59 UTC, theRenard commented on src/guide/installation.md
> +In production, raccomandiamo di puntare a un numero specifico di versione e build per evitare malfunzionamenti inaspettati causati da nuove versioni.
e se al posto di puntare mettessimo semplicemente usare (utilizzare) ? `raccomandiamo di usare un numero specifico...`

2021-03-25 07:59 UTC, theRenard commented on src/guide/installation.md
> +Se vuoi evitare di utilizzare dei build tool ma non puoi usare una CDN in production, allora puoi scaricare i file `.js` rilevanti e caricarli sul tuo web server. Puoi successivamente includerli con
non sono sicuro di `production` ma non mi viene in mente altro. In Francia usiamo `en prod`, se non ci viene in mente altro lasciamo così :)

2021-03-25 07:59 UTC, theRenard commented on src/guide/installation.md
> +I file possono essere visitati e scaricati da una CDN come [unpkg](https://unpkg.com/browse/vue@next/dist/) o [jsDelivr](https://cdn.jsdelivr.net/npm/vue@next/dist/). I diversi file sono [spiegati su
`consultati` al posto di `visitati` ? `vari file` al posto di `diversi file`, che ne pensi ?

2021-03-25 07:59 UTC, theRenard commented on src/guide/installation.md
> +Vue fornisce una [CLI ufficiale](https://github.com/vuejs/vue-cli) per lo scaffolding rapido di Single Page Applications ambiziose. Fornisce un setup di sviluppo completo per un workflow di sviluppo
Penso si possa togliere un `sviluppo` in eccesso `Fornisce un setup di sviluppo completo per un workflow frontend moderno`. 

builds -> build

2021-03-25 07:59 UTC, theRenard commented on src/guide/installation.md
>  La CLI assume conoscenza pregressa di Node.js e degli strumenti di build ad esso associati. Se Vue o gli strumenti di build per il frontend ti sono nuovi, ti suggeriamo fortemente di leggere <a href=
`fortemente` si può sostituire con `caldamente`, che ne pensi ?

2021-03-25 07:59 UTC, theRenard commented on src/guide/installation.md
> +Può accadere, che nel caso in cui il tuo username abbia uno spazio al suo interno come in 'Mike Baker', Vite fallisce. Prova con:
Due proposizioni: 

1. o usare `Vite fallisca` 
2. o togliere il può accadere e mettere un `se`

2021-03-25 07:59 UTC, theRenard commented on src/guide/installation.md
> +- Non produce builds minimizzate (da fare con il resto del codice dopo il bundling)
Non sono sicurissimo della traduzione di minified con minimizzate, magari `compresse` ? Oppure lasciare minified punto e basta? Comunque si capisce

2021-03-25 07:59 UTC, theRenard commented on src/guide/installation.md
> +  - Questo significa che **puoi** installare/importare queste dipendenze individualmente senza finire con diverse instanze della stessa dipendenza, ma devi assicurarti che risolvono tutte alla stessa
Questa frase la trovo un po' arzigogolata non è facile tradurla in inglese... ho dei dubbi sul `finire` e sul `risolvere` provo una alternativa: `Questo significa che **puoi** installare/importare queste dipendenze individualmente senza avere istanze multiple della stessa dipendenza, devi però assicurarti che usino tutte la stessa versione.`

2021-03-25 07:59 UTC, theRenard commented on src/guide/installation.md
> +  - `vue.esm-bundler.js`: include il compilatore di runtime. Usa questo se stai già usando un bundler ma vuoi comunque una compilazione a runtime dei template (es. template in-DOM or templates tramit
Penso sia `per creare un alias`

2021-03-25 07:59 UTC, theRenard commented on src/guide/installation.md
> +- Se vuoi creare un bundle della tua app con webpack con `target: 'node'` ed esternalizzare propriamente `vue`, questa è la build che sarà caricata.
propriamente si può semplicemente togliere credo, oppure usare `correttamente` ?

2021-03-25 07:59 UTC, theRenard commented on src/guide/installation.md
> +- I file dev/prod sono pre-built, ma il file più appropriato è richiesto automaticamente a seconda di `process.env.NODE_ENV`.
Questa a mio avviso parte male in inglese, ma senza traduzione accanto faccio davvero fatica a capire cosa voglia dire in italiano. Possiamo rinunciare alla traduzione 1:1 e rivisitarla per darle un senso compiuto, non so se ti viene in mente una soluzione diversa...

2021-03-25 07:59 UTC, theRenard commented on src/guide/installation.md
> +Se hai bisogno di compilare i template nel client (es. passare una stringa all'option template, o agganciarsi ad un elemento usando il suo HTML in-DOM come template), avrai bisogno del compilatore e
Agganciarsi mi piace, penso che Mount lo troveremo un po' ovunque nella traduzione, occorre solo verificare che funzioni in tutti i casi 👌

2021-03-27 11:51 UTC, NatanCieplinski commented on src/guide/installation.md
>  ## Note di Rilascio
Direi `note della release`.

2021-03-27 11:54 UTC, NatanCieplinski commented on src/guide/installation.md
> +Se vuoi evitare di utilizzare dei build tool ma non puoi usare una CDN in production, allora puoi scaricare i file `.js` rilevanti e caricarli sul tuo web server. Puoi successivamente includerli con
Io direi di lasciare `production` ovunque. In italia si usa `prod` nel colloquiale, ma non so se è il termine corretto.

2021-03-27 11:56 UTC, NatanCieplinski commented on src/guide/installation.md
>  La CLI assume conoscenza pregressa di Node.js e degli strumenti di build ad esso associati. Se Vue o gli strumenti di build per il frontend ti sono nuovi, ti suggeriamo fortemente di leggere <a href=
Direi di si, lo inserisco anche nella wiki

2021-03-27 12:03 UTC, NatanCieplinski commented on src/guide/installation.md
> +- Non produce builds minimizzate (da fare con il resto del codice dopo il bundling)
Minimizzare come termine esiste ([esempio](https://www.html.it/articoli/ottimizzazione-javascript-e-performance-del-sito/)).

2021-03-27 12:04 UTC, NatanCieplinski commented on src/guide/installation.md
> +  - Questo significa che **puoi** installare/importare queste dipendenze individualmente senza finire con diverse instanze della stessa dipendenza, ma devi assicurarti che risolvono tutte alla stessa
Ti ringrazio, questa è stata decisamente la frase più difficile da tradurre.

2021-03-27 12:11 UTC, NatanCieplinski commented on src/guide/installation.md
> +- I file dev/prod sono pre-built, ma il file più appropriato è richiesto automaticamente a seconda di `process.env.NODE_ENV`.
Bella domanda. La sezione è abbastanza recente, 3 settimane fa se non ricordo male, quindi direi che non è matura neanche dal lato inglese. Non ho idea di come procedere.

2021-03-28 07:30 UTC, theRenard commented on src/guide/installation.md
> +- I file dev/prod sono pre-built, ma il file più appropriato è richiesto automaticamente a seconda di `process.env.NODE_ENV`.
Lasciamo così per ora, vediamo gli sviluppi

2021-03-28 07:30 UTC, theRenard commented on src/guide/installation.md
>  ## Note di Rilascio
Ok, ti lascio modificare e aggiungo al wiki

2021-03-29 09:51 UTC, theRenard approved these changes
🙆‍♂️ Approved

2021-03-29 09:53 UTC, merged