Traduzione guide/migration/introduction.md
NatanCieplinski/docs-next-it pull request #146
Opened 2021-03-28 13:21 UTC by rbattiato

Closes #55

2021-03-28 13:27 UTC, rbattiato commented
Ci sono alcune ambiguità su cui dovremmo decidere per coerenza interna al progetto, ad esempio se e come tradurre "breaking changes" (al momento l'ho tradotto con "modifiche importanti") ed altre espressioni che sarebbe meglio lasciare in Inglese.
Il file è già pronto a parte questi dubbi su cui preferirei avere vostro feedback

@NatanCieplinski @theRenard

2021-03-28 14:15 UTC, NatanCieplinski commented
Dato che capita in più pull request direi che è il caso di aprire una discussion apposita altrimenti le discussioni finiscono sparse tra tutte le PR

2021-03-28 14:22 UTC, rbattiato commented
> 
> 
> Dato che capita in più pull request direi che è il caso di aprire una discussion apposita altrimenti le discussioni finiscono sparse tra tutte le PR

Ottima idea! Direi che bisogna cominciare da un elenco di tutti i potenziali termini
Vado io o ci pensi tu?

2021-03-28 21:16 UTC, NatanCieplinski commented
Se hai già incontrato qualche termine scrivi pure. Nel frattempo nella sezione wiki abbiamo compilato già una lista di quelli già incontrati

2021-03-30 06:40 UTC, theRenard commented
Questa PR è ok oppure ha bisogno di una rilettura ?

2021-03-30 06:44 UTC, NatanCieplinski commented
@theRenard fin quando è in draft è da contare come non pronta per una review. O almeno queste sono le convezioni su GitHub

2021-03-30 07:08 UTC, theRenard commented
Ok 👍

2021-03-30 07:32 UTC, rbattiato commented
> 
> 
> Questa PR è ok oppure ha bisogno di una rilettura ?

Manca sostituire alcuni termini come da convenzioni e una rilettura finale prima di passarla in Ready for review

2021-04-03 14:43 UTC, NatanCieplinski requested changes

2021-04-03 14:43 UTC, NatanCieplinski commented on src/guide/migration/introduction.md
> +- [Nuove caratteristiche di rilievo](#notable-new-features)
Direi più `nuove funzionalità di rilievo`

2021-04-03 14:43 UTC, NatanCieplinski commented on src/guide/migration/introduction.md
> +Questa guida è rivolta principalmente agli utenti con precedente esperienza su Vue 2 che vogliono conoscere le nuove caratteristiche ed i cambiamenti di Vue 3. **Non è necessario leggerla per intero
`con precedente esperienza su Vue 2...` => `con precedente esperienza con Vue 2`

2021-04-03 14:43 UTC, NatanCieplinski commented on src/guide/migration/introduction.md
> +- [Opzione Emits dei componenti](/guide/component-custom-events.html)
Questo lo lascerei in inglese perchè credo si riferisca all Option API

2021-04-03 14:43 UTC, NatanCieplinski commented on src/guide/migration/introduction.md
> +### Funzione Render
Questa non andrebbe tradotta che è una funzionalità di Vue

2021-04-03 14:43 UTC, NatanCieplinski commented on src/guide/migration/introduction.md
> +- [L'API della funzione Render è stata modificata](/guide/migration/render-function-api.html)
Stessa cosa qui

2021-04-03 14:43 UTC, NatanCieplinski commented on src/guide/migration/introduction.md
> +### Altre modifiche minori
Toglierei `minori`, suona molto strano in italiano

2021-04-03 14:43 UTC, NatanCieplinski commented on src/guide/migration/introduction.md
> +Stiamo lavorando ad una nuova versione degli strumenti per lo sviluppatore con una nuova interfaccia utente e funzionamenti interni rifattorizzati per supportare versioni di Vue multiple. La nuova ve
Qui l'italiano è molto traduttore style, direi qualcosa tipo `ad una nuova versione degli strumenti per sviluppatori con una nuova interfaccia e la possibilità di supportare multiple versioni di Vue`

2021-04-03 14:43 UTC, NatanCieplinski commented on src/guide/migration/introduction.md
> +## Supporto delle librerie
Qui corrisponde più a `librerie di supporto` secondo me

2021-04-03 14:43 UTC, NatanCieplinski commented on src/guide/migration/introduction.md
> +- [Supporto delle librerie](#supporting-libraries)
Direi `Librerie di supporto`

2021-04-04 15:24 UTC, rbattiato commented on src/guide/migration/introduction.md
> +- [Nuove caratteristiche di rilievo](#notable-new-features)
Ok!

2021-04-04 15:26 UTC, rbattiato commented on src/guide/migration/introduction.md
> +Questa guida è rivolta principalmente agli utenti con precedente esperienza su Vue 2 che vogliono conoscere le nuove caratteristiche ed i cambiamenti di Vue 3. **Non è necessario leggerla per intero
`con precedente esperienza nell'uso di Vue 2` per evitare la ripetizione di "con"?
Anche `con esperienza pregressa nell'uso di Vue 2` o simili

2021-04-04 15:26 UTC, rbattiato commented on src/guide/migration/introduction.md
> +- [Opzione Emits dei componenti](/guide/component-custom-events.html)
Ok

2021-04-04 15:29 UTC, rbattiato commented on src/guide/migration/introduction.md
> +### Funzione Render
In quanto a `Render` ci sta, è sia una funzionalità di Vue che un termine tecnico informatico difficilmente traducibile in italiano.
Ma `Function`? Si parla di una normale funzione JavaScript, concetto generalmente conosciuto in italiano come `Funzione`.

2021-04-04 15:31 UTC, rbattiato commented on src/guide/migration/introduction.md
> +### Altre modifiche minori
A me è capitato di vederlo scritto in giro, scrivendo in due secondi su Google c'è [questa pagina](https://it.wikipedia.org/wiki/Aiuto:Modifica_minore) di Wikipedia che parla di modifiche "minori", così come usiamo dire "maggiore" delle cose più importanti ecc.
Comunque eventualmente anche lasciare "Altre modifiche" per me è ok, il significato passa

2021-04-04 15:34 UTC, rbattiato commented on src/guide/migration/introduction.md
> +Stiamo lavorando ad una nuova versione degli strumenti per lo sviluppatore con una nuova interfaccia utente e funzionamenti interni rifattorizzati per supportare versioni di Vue multiple. La nuova ve
Ok per tutto, ma che ne dici di `con una nuova interfaccia ed il supporto a multiple versioni di Vue` o `con una nuova interfaccia ed il supporto a versioni di Vue multiple`?

2021-04-04 15:37 UTC, rbattiato commented on src/guide/migration/introduction.md
> +## Supporto delle librerie
Il punto è che la sezione che segue non discute prettamente di librerie che vanno a supporto di Vue ma piuttosto dello stato attuale delle librerie dell'ecosistema Vue e di a che punto sono con il loro supporto a Vue 3 rispetto a Vue 2. Per esempio, Vuex e Vue Router (presenti nell'elenco) non sono librerie di supporto ma importanti elementi dell'ecosistema Vue, chiamarle "librerie di supporto" sminuisce un po' la loro importanza secondo me

2021-04-04 15:37 UTC, rbattiato commented on src/guide/migration/introduction.md
> +- [Supporto delle librerie](#supporting-libraries)
Come sopra

2021-04-04 17:10 UTC, NatanCieplinski commented on src/guide/migration/introduction.md
> +Questa guida è rivolta principalmente agli utenti con precedente esperienza su Vue 2 che vogliono conoscere le nuove caratteristiche ed i cambiamenti di Vue 3. **Non è necessario leggerla per intero
Si così è ancora meglio

2021-04-04 17:13 UTC, NatanCieplinski commented on src/guide/migration/introduction.md
> +### Funzione Render
In teoria si, in pratica `render function` lo considero un pò un concetto a sè del mondo frontend. Immagina una persona che decide di usarla per un componente custom. Se su google cerca `Cos'è una funzione render Vue` si ritroverà risultati molto diversi rispetto a `Cos'è una render function Vue` (prova tu stesso)

2021-04-04 17:14 UTC, NatanCieplinski commented on src/guide/migration/introduction.md
> +### Altre modifiche minori
Tra le due scegli tu, come dici tu insieme direi di no

2021-04-04 17:15 UTC, NatanCieplinski commented on src/guide/migration/introduction.md
> +Stiamo lavorando ad una nuova versione degli strumenti per lo sviluppatore con una nuova interfaccia utente e funzionamenti interni rifattorizzati per supportare versioni di Vue multiple. La nuova ve
Se penso all'espressione `multiple volte` mi viene naturale mettere il `multiple` prima

2021-04-04 17:17 UTC, NatanCieplinski commented on src/guide/migration/introduction.md
> +## Supporto delle librerie
Che ne dici allora se andiamo per `Supporto nell'ecosistema?`. Perchè `supporto delle librerie` mi fa pensare a come Vue supporti la versione attuale delle librerie, mentre invece sono le librerie a dover supportare la nuova versione di Vue

2021-04-04 17:19 UTC, rbattiato commented on src/guide/migration/introduction.md
> +## Supporto delle librerie
Ok per  `Supporto nell'ecosistema`. Mi è anche venuto in mente un generico `Stato del supporto`, ma non ne sono sicuro. Se ti convince andiamo con la prima

2021-04-04 17:19 UTC, rbattiato commented on src/guide/migration/introduction.md
> +Stiamo lavorando ad una nuova versione degli strumenti per lo sviluppatore con una nuova interfaccia utente e funzionamenti interni rifattorizzati per supportare versioni di Vue multiple. La nuova ve
Ok

2021-04-04 17:20 UTC, rbattiato commented on src/guide/migration/introduction.md
> +### Altre modifiche minori
Ok

2021-04-04 17:20 UTC, rbattiato commented on src/guide/migration/introduction.md
> +### Funzione Render
Va bene

2021-04-04 17:20 UTC, rbattiato commented on src/guide/migration/introduction.md
> +Questa guida è rivolta principalmente agli utenti con precedente esperienza su Vue 2 che vogliono conoscere le nuove caratteristiche ed i cambiamenti di Vue 3. **Non è necessario leggerla per intero
Perfetto

2021-04-04 17:21 UTC, NatanCieplinski commented on src/guide/migration/introduction.md
> +## Supporto delle librerie
Direi la prima. Oppure `Stato dell'ecosistema Vue`. Insomma hai capito il concetto spero 😅

2021-04-04 17:23 UTC, rbattiato commented on src/guide/migration/introduction.md
> +## Supporto delle librerie
Ok per `Supporto nell'ecosistema`

2021-04-04 17:40 UTC, NatanCieplinski approved these changes
🛳

2021-04-07 23:42 UTC, merged