guide/migration/suspense.md
NatanCieplinski/docs-next-it pull request #150
Opened 2021-03-29 11:01 UTC by theRenard

2021-03-30 22:01 UTC, NatanCieplinski requested changes

2021-03-30 22:01 UTC, NatanCieplinski commented on src/guide/migration/suspense.md
> +L'esempio seguente mostra come nidificare questi componenti in modo che si comportino tutti come previsto. Per combinazioni più semplici puoi rimuovere i componenti che non ti servono:
Nidificare mi piace di più parola ma credo annidare sia più chiara più velocemente. Che ne pensi? Nel caso lo aggiungo alla wiki

2021-03-31 08:41 UTC, theRenard commented on src/guide/migration/suspense.md
> +Non dovrebbe essere utilizzato nelle applicazioni di produzione.
di `production` o _in_ `production` ?

2021-03-31 08:46 UTC, theRenard commented on src/guide/migration/suspense.md
> +L'esempio seguente mostra come nidificare questi componenti in modo che si comportino tutti come previsto. Per combinazioni più semplici puoi rimuovere i componenti che non ti servono:
Annidare 👌

2021-03-31 09:09 UTC, theRenard commented
Ad una nuova rilettura mi sono accorto che l'italiano era un po' farraginoso ed ho preferito riscrivere qualche frase, mi spiace se ti costringo a rileggere tutto il malloppo 😅

2021-03-31 09:11 UTC, theRenard commented on src/guide/migration/suspense.md
> +:::avvertimento sperimentale
Ok, il contenuto di badges

`---
badges:
  - new
---`

dovrebbe essere tradotto in `novità` ?

2021-03-31 09:54 UTC, NatanCieplinski commented on src/guide/migration/suspense.md
> +:::avvertimento sperimentale
Non ho capito a cosa ti stai riferendo..

2021-03-31 09:55 UTC, NatanCieplinski commented on src/guide/migration/suspense.md
> +Non dovrebbe essere utilizzato nelle applicazioni di produzione.
In questo caso *in*. Ma ad esempio con `ambiente` dovrebbe essere l'ambiente *di* production.

2021-03-31 09:56 UTC, NatanCieplinski commented
Va benissimo perchè la forza di Vue per i principianti è la doc, e una buona traduzione non può che aiutare

2021-03-31 09:59 UTC, theRenard commented on src/guide/migration/suspense.md
> +:::avvertimento sperimentale
giusto. Mi riferisco al badge in testa, ex

![image](https://user-images.githubusercontent.com/61255863/113126956-7da88a80-9218-11eb-8663-da67eaa2aff0.png)

2021-03-31 11:16 UTC, theRenard commented on src/guide/migration/suspense.md
> +:::avvertimento sperimentale
Questo lo vediamo successivamente

2021-03-31 11:16 UTC, theRenard commented
Correzioni fatte

2021-03-31 13:00 UTC, NatanCieplinski approved these changes
LGTM

2021-03-31 13:59 UTC, merged