guide/introduction.md
NatanCieplinski/docs-next-it pull request #151
Opened 2021-03-30 22:41 UTC by NatanCieplinski

Closing #38 

## Description of Problem

## Proposed Solution

## Additional Information

2021-03-31 15:01 UTC, theRenard requested changes
Super lavoro, complimenti! Ho suggerito qualche piccolo cambiamento e identificato qualche refuso.

2021-03-31 15:01 UTC, theRenard commented on src/guide/introduction.md
> +Abbiamo introdotto le funzionalità più base del core di Vue.js - il resto di questa guida spiegherà loro e altre funzionalità avanzate molto più in dettaglio, quindi assicurati di leggerla tutta!
Suggerimento:

`Abbiamo introdotto le funzionalità di base del core di Vue.js - il resto di questa guida le spiegherà più in dettaglio, insieme ad altre funzionalità ancora più avanzate, assicurati quindi di leggerla tutta!`

2021-03-31 20:11 UTC, NatanCieplinski commented on src/guide/introduction.md
> +Se ti piacerebbe scoprire di più Vue prima di continuare la lettura, abbiamo <a id="modal-player" class="vuemastery-trigger"  href="#">creato un video</a> che ne illustra i prinicipi alla base e un p
Ho scelto la seconda

2021-03-31 20:13 UTC, NatanCieplinski commented on src/guide/introduction.md
> +La guida ufficiale assume una conoscenza intermedia di HTLM, CSS e JavaScript. Se sei completamente nuovo allo sviluppo frontend, potrebbe non essere una buona idea cominciare direttamente con un fra
`presuppone` mi piace di più di `assume`, ho messo quello.

Sia `novizio` che `digiuno` mi sembrano molto burocratici, che ne dici per un grosso cambio in `se questo è il tuo primo approccio allo sviluppo frontend...`?

2021-03-31 20:15 UTC, NatanCieplinski commented on src/guide/introduction.md
> +La pagina di [Installazione](installation.md) fornisce più opzioni per installare Vue. Nota: **non** raccomandiamo che i principianti comincino con la `vue-cli`, specialmente se non ancora familiari
Il mio treno di pensieri è stato `la linea di comando` => `la command line` => `la Vue-cli`

2021-03-31 20:17 UTC, NatanCieplinski commented on src/guide/introduction.md
> +Abbiamo già creato la nostra prima app Vue! Questa assomiglia molto al fare il rendering a stringhe template, ma Vue al suo interno ha fatto tanto lavoro. I dati e il DOM ora sono collegati, e ora tu
Caspita così mi piace molto di più! Mi ricorda l'aspetto "friendly" della guida letta in inglese

2021-03-31 20:23 UTC, NatanCieplinski commented on src/guide/introduction.md
> +Quì abbiamo incontrato qualcosa di nuovo. L'attributo `v-bind` che vedi si chiama **directive**. Le direttive hanno il prefisso `v-` per indicare che sono attributi speciali forniti da Vue, e come av
Integrato i primi commenti, ma `istanza in corso` non mi convince perchè mi fa pensare che una volta finite le operazioni l'istanza muore, mentre `attualmente attiva` rispecchia il comportamento di Vue, che quando cambia un dato comincia ad accedere a tutte le istanze dei componenti che lo hanno come dipendenza, per applicare le modifiche. Che ne pensi?

2021-03-31 20:24 UTC, NatanCieplinski commented on src/guide/introduction.md
> +## Gestione dell'Input Utente
Quà si riferisce all'input dei form, non ad una generica interazione. Però `Gestione dell'Input **da** utente` potrebbe suonare meglio, che dici?

2021-03-31 20:26 UTC, NatanCieplinski commented on src/guide/introduction.md
> +Vue fornisce anche la direttiva `v-model` che rende il binding a due vie tra l'input del form e lo state dell'applicazione un gioco da ragazzi:
All'università binding ce lo hanno detto sempre in inglese. `A due vie` invece mi è sembrato che non suonasse troppo male rispetto a `two-ways`

2021-03-31 20:27 UTC, NatanCieplinski commented on src/guide/introduction.md
> +Questo esempio dimostra che possiamo fare il bind di dati non solo a testi e attributi, ma anche alla **struttura** del DOM. Inoltre, Vue fornisce anche un potente sistema di effetti sulle transizion
Qui più che alla proprietà `data` si riferisce al concetto generico di dato credo, perchè si può fare il bind anche su props e computed

2021-03-31 20:30 UTC, NatanCieplinski commented on src/guide/introduction.md
>    template: `<li>This is a todo</li>`
Non ho capito 😅

2021-04-01 07:06 UTC, theRenard approved these changes
Ottimo!

2021-04-01 07:06 UTC, theRenard commented on src/guide/introduction.md
> +Vue (pronunciato /vjuː/, come **viu**) è un **framework progressivo** per lo sviluppo di interfaccie grafiche. Diversamente da altri framework monolitici, Vue è progettato dalla base per essere adott
Ok lasciamola com'è

2021-04-01 07:06 UTC, theRenard commented on src/guide/introduction.md
> +La pagina di [Installazione](installation.md) fornisce più opzioni per installare Vue. Nota: **non** raccomandiamo che i principianti comincino con la `vue-cli`, specialmente se non ancora familiari
giusto

2021-04-01 07:06 UTC, theRenard commented on src/guide/introduction.md
> +## Gestione dell'Input Utente
No lascia pure com'è

2021-04-01 07:06 UTC, theRenard commented on src/guide/introduction.md
> +Questo esempio dimostra che possiamo fare il bind di dati non solo a testi e attributi, ma anche alla **struttura** del DOM. Inoltre, Vue fornisce anche un potente sistema di effetti sulle transizion
ok

2021-04-01 07:06 UTC, theRenard commented on src/guide/introduction.md
>    template: `<li>This is a todo</li>`
Mi riferivo al `this is a todo` :)

2021-04-01 07:13 UTC, merged