guide/migration/render-function-api.md
NatanCieplinski/docs-next-it pull request #152
Opened 2021-04-07 14:48 UTC by theRenard

Fixes NatanCieplinski/docs-next-it#129

## Description of Problem

## Proposed Solution

## Additional Information

2021-04-11 11:05 UTC, NatanCieplinski requested changes
I primi due commenti sono solo due suggerimenti a tua completa discrezione

2021-04-11 11:05 UTC, NatanCieplinski commented on src/guide/migration/render-function-api.md
> +Questa modifica non riguarda gli utenti di `<template>`.
Qui credo sia più `gli utilizzatori` che `gli utenti`. Oppure in forma più verbosa `Questa modifica non influenza chi utilizza i template`

2021-04-11 11:05 UTC, NatanCieplinski commented on src/guide/migration/render-function-api.md
> +Per altre informazioni su come funziona `setup()`, leggi la guida della [Composition API](/guide/composition-api-introduction.html).
Non sarebbe più corretto `leggi la guida **alla** Composition API`?

2021-04-11 11:05 UTC, NatanCieplinski commented on src/guide/migration/render-function-api.md
> +- Per le build UMD / browser, si dovrebbe prima cercare Vue.h globale e `require` come ripiego.
`globale e require come ripiego` => `globale e usare require solo come ripiego`.  oppure stessa frase ma senza il `solo`.

2021-04-16 09:06 UTC, theRenard commented
tutto corretto! 😁

2021-04-16 09:29 UTC, NatanCieplinski approved these changes
🛳

2021-04-16 10:24 UTC, merged